# Dockerfile.collector
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY collector/ ./collector/

WORKDIR /app/collector

CMD ["python", "-u", "consumer.py"]